esphome:
  name: air-sensor

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
#esp32_improv:
#  authorizer: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

esp32_ble_tracker:

ble_client:
  - mac_address: C9:3E:F1:9B:E7:77
    id: heart_rate_monitor

sensor:
  - platform: senseair
    co2:
      name: CO₂
    update_interval: 30s
  - platform: sht3xd
    i2c_id: bus_a
    address: 0x44
    update_interval: 10s
    temperature:
      name: Temperature
    humidity:
      name: Humidity
  - platform: ble_client
    ble_client_id: heart_rate_monitor
    id: heart_rate_measurement
    name: "Heart rate measurement"
    service_uuid: '180d'
    characteristic_uuid: '2a37'
    notify: true
    lambda: |-
      uint16_t heart_rate_measurement = x[1];
      if (x[0] & 1) {
          heart_rate_measurement += (x[2] << 8);
      }
      return (float)heart_rate_measurement;
    icon: 'mdi:heart'
    unit_of_measurement: 'bpm'   
