esphome:
  name: bowflex-hr-monitor

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

esp32_ble_tracker:

ble_client:
  - id: heart_rate_monitor
    mac_address: C9:3E:F1:9B:E7:77

sensor:
  - id: heart_rate_measurement
    name: "Heart rate measurement"
    icon: 'mdi:heart'
    unit_of_measurement: 'bpm'
    platform: ble_client
    ble_client_id: heart_rate_monitor
    service_uuid: '180d'
    characteristic_uuid: '2a37'
    notify: true
    lambda: |-
      uint16_t heart_rate_measurement = x[1];
      if (x[0] & 1) {
          heart_rate_measurement += (x[2] << 8);
      }
      return (float)heart_rate_measurement;
