esphome:
  name: bowflex-hr-monitor

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

esp32_ble_tracker:

ble_client:
  - id: heart_rate_monitor
    mac_address: C9:3E:F1:9B:E7:77

