substitutions:
  devicename: ESP32-C3-12F

esphome:
  name: esp32-c3-12f
#  platformio_options:
#    platform: https://github.com/platformio/platform-espressif32#v3.4.0
#    platform_packages:
#      - framework-arduinoespressif32@https://github.com/espressif/arduino-esp32#2.0.1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    version: recommended
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
# Not working on esp-idf
#esp32_improv:
#  authorizer: none

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
#  encryption:
#    key: !secret api_encryption_key

ota:
  password: !secret ota_password

output:
  - platform: gpio
    id: led
    pin:
      number: 9
      inverted: True

light:
  - platform: binary
    name: "Board LED"
    output: led
