external_components:
  source: github://SebastianBar/esphome@openhaystack
  components: [openhaystack]
  refresh: 60s

esphome:
  name: esp32-c3-12f
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # Specific to Bluetooth usage
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Payload size fix - Extend Watchdog timeout, should be "pre-flashed"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# Enable ESPHome status output though D5 PCB LED
status_led:
  pin:
    number: GPIO9
    inverted: True

openhaystack:
  type: IBEACON
  uuid: 41B9C8F0-A9BA-4C93-8A9A-E7F0D7AF16B8
  key: !secret openhaystack_key
