esphome:
  name: humidifier

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up provisioning Wi-Fi credentials to the device over BLE
esp32_improv:
  authorizer: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:

switch:
  - platform: gpio
    name: "Humidifier"
    pin: 2
    inverted: False
    id: humidifierSwitch
