substitutions:
  devicename: NEXXT Device

esphome:
  name: nexxt-mod-test
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32#feature/arduino-idf-master #feature/arduino-upstream
    platform_packages:
      - framework-arduinoespressif32@https://github.com/espressif/arduino-esp32#2.0.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    version: latest

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
#  encryption:
#    key: !secret api_encryption_key

ota:
  password: !secret ota_password

status_led:
  pin:
    number: GPIO20
    inverted: True

binary_sensor:
  - platform: gpio
    name: ${devicename} Button
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: plug_top_left

output:
  - platform: gpio
    pin:
      number: GPIO9
      inverted: true
    id: red_led

light:
  - platform: binary
    name: ${devicename} Red LED
    output: red_led
#    default_transition_length: 300ms

switch:
    # Platform controls
  - platform: restart
    name: ${devicename} Restart
  - platform: safe_mode
    name: ${devicename} Restart (Safe Mode)
    # Plugs
  - platform: gpio
    id: plug_top_left
    name: ${devicename} Plug - Top Left
    pin: GPIO2
  - platform: gpio
    id: plug_top_right
    name: ${devicename} Plug - Top Right
    pin: GPIO3
  - platform: gpio
    id: plug_bottom_left
    name: ${devicename} Plug - Bottom Left
    pin: GPIO4
  - platform: gpio
    id: plug_bottom_right
    name: ${devicename} Plug - Bottom Right
    pin: GPIO5
    # USB
  - platform: gpio
    id: usb_top_left
    name: ${devicename} USB - Top Left
    pin: GPIO8
  - platform: gpio
    id: usb_top_right
    name: ${devicename} USB - Top Right
    pin: GPIO18
  - platform: gpio
    id: usb_bottom_left
    name: ${devicename} USB - Bottom Left
    pin: GPIO19
  - platform: gpio
    id: usb_bottom_right
    name: ${devicename} USB - Bottom Right
    pin: GPIO21 # Not working --- TX pin, always on?
    mode: INPUT_PULLUP

