substitutions:
  devicename: NEXXT Device

esphome:
  name: nexxt-mod-test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
#esp32_improv:
#  authorizer: none

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
#  encryption:
#    key: !secret api_encryption_key

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    internal: true
    name: ${devicename} Button
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: red_led
      - light.toggle: blue_led
      - switch.toggle: plug_top_left

output:
  - platform: gpio
    id: red_led_gpio
    pin:
      number: GPIO9
      inverted: true

light:
  - platform: status_led
    internal: true
    id: blue_led
    name: ${devicename} Blue LED
    pin:
      number: GPIO20
      inverted: True
  - platform: binary
    internal: true
    id: red_led
    name: ${devicename} Red LED
    output: red_led_gpio

switch:
    # Platform controls
  - platform: restart
    name: ${devicename} Restart
  - platform: safe_mode
    name: ${devicename} Restart (Safe Mode)
    # Plugs
  - platform: gpio
    id: plug_top_left
    name: ${devicename} Plug - Top Left
    icon: mdi:power-socket-it
    pin: GPIO2
  - platform: gpio
    id: plug_top_right
    name: ${devicename} Plug - Top Right
    icon: mdi:power-socket-it
    pin: GPIO3
  - platform: gpio
    id: plug_bottom_left
    name: ${devicename} Plug - Bottom Left
    icon: mdi:power-socket-it
    pin: GPIO4
  - platform: gpio
    id: plug_bottom_right
    name: ${devicename} Plug - Bottom Right
    icon: mdi:power-socket-it
    pin: GPIO5
    # USB
  - platform: gpio
    id: usb_top_left
    name: ${devicename} USB - Top Left
    icon: mdi:usb-port
    pin: GPIO8
  - platform: gpio
    id: usb_top_right
    name: ${devicename} USB - Top Right
    icon: mdi:usb-port
    pin: GPIO18
  - platform: gpio
    id: usb_bottom_left
    name: ${devicename} USB - Bottom Left
    icon: mdi:usb-port
    pin: GPIO19
  - platform: gpio
    id: usb_bottom_right
    name: ${devicename} USB - Bottom Right
    icon: mdi:usb-port
    pin:
      number: GPIO21 # Not working --- TX pin, always on? - ON 2.4v, OFF 0.99v
      drive_strength: 10mA
#      mode:
#        pullup: true
