substitutions:
  devicename: NEXXT Device


esphome:
  name: nexxt-mod-test
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32#v3.4.0
    platform_packages:
      - framework-arduinoespressif32@https://github.com/espressif/arduino-esp32#2.0.1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    version: latest
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
# Not working on esp-idf
#esp32_improv:
#  authorizer: none

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
#  encryption:
#    key: !secret api_encryption_key

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    internal: true
    name: ${devicename} Button
    pin:
      number: 1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: red_led
      - light.toggle: blue_led
      - switch.toggle: plug_top_left

output:
  - platform: gpio
    id: red_led_gpio
    pin:
      number: 9
      inverted: true

light:
  - platform: status_led
    internal: true
    id: blue_led
    name: ${devicename} Blue LED
    pin:
      number: 20
      inverted: True
  - platform: binary
    internal: true
    id: red_led
    name: ${devicename} Red LED
    output: red_led_gpio

switch:
    # Platform controls
  - platform: restart
    name: ${devicename} Restart
  - platform: safe_mode
    name: ${devicename} Restart (Safe Mode)
    # Plugs
  - platform: gpio
    id: plug_top_left
    name: ${devicename} Plug - Top Left
    pin: 2
  - platform: gpio
    id: plug_top_right
    name: ${devicename} Plug - Top Right
    pin: 3
  - platform: gpio
    id: plug_bottom_left
    name: ${devicename} Plug - Bottom Left
    pin: 4
  - platform: gpio
    id: plug_bottom_right
    name: ${devicename} Plug - Bottom Right
    pin: 5
    # USB
  - platform: gpio
    id: usb_top_left
    name: ${devicename} USB - Top Left
    pin: 8
  - platform: gpio
    id: usb_top_right
    name: ${devicename} USB - Top Right
    pin: 18
  - platform: gpio
    id: usb_bottom_left
    name: ${devicename} USB - Bottom Left
    pin: 19
  - platform: gpio
    id: usb_bottom_right
    name: ${devicename} USB - Bottom Right
    pin:
      number: 21 # Not working --- TX pin, always on? - ON 2.4v, OFF 0.99v
#      mode:
#        pullup: true
