external_components:
  - source:
      type: local
      path: custom_components
    components: [openhaystack]

esphome:
  name: openhaystack-demo
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

openhaystack:
  uuid: 41B9C8F0-A9BA-4C93-8A9A-E7F0D7AF16B8
  key: !secret openhaystack_key
