external_components:
  source: github://SebastianBar/esphome@openhaystack
  components: [openhaystack]
  refresh: 60s

esphome:
  name: openhaystack-demo
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

openhaystack:
  type: IBEACON
  uuid: 41B9C8F0-A9BA-4C93-8A9A-E7F0D7AF16B8
  key: !secret openhaystack_key
