external_components:
  source: github://SebastianBar/esphome@openhaystack
  components: [openhaystack]
  refresh: 60s

esphome:
  name: openhaystack-demo
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # Specific to Bluetooth usage
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Payload size fix - Extend Watchdog timeout, should be "pre-flashed"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

openhaystack:
  type: IBEACON
  uuid: 41B9C8F0-A9BA-4C93-8A9A-E7F0D7AF16B8
  key: !secret openhaystack_key
