external_components:
  source: github://jesserockz/esphome@tuya-new
  components: [tuya_new]

esphome:
  name: somela-black-glass-connect

esp8266:
  board: esp8285
  framework:
    version: latest

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Somela-Black-Glass-Connect"
    password: "3lUaUnNEk4hN"

captive_portal:

# Make sure logging is not using the serial port
logger:
  #level: VERY_VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

# Register the Tuya MCU connection
tuya_new:

climate:
  - platform: tuya_new
    name: "Somela Black Glass Connect"
    switch_datapoint: 0
#    active_state_datapoint: 6
    target_temperature_datapoint: 7
    current_temperature_datapoint: 10
    hysteresis: 2
    visual:
      min_temperature: 5
      max_temperature: 50
      temperature_step: 1
