substitutions:
  device_name: Sonoff POWR2
  device_serial: 0013903732

esphome:
  name: sonoff-powr2-0013903732

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} ${device_serial}
    password: hJ3hJJCSlslr

captive_portal:

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# Enable ESPHome status output though green LED
status_led:
  pin:
    number: GPIO13
    inverted: True

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${device_name} ${device_serial} Button
    internal: true
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: ${device_name} ${device_serial} WiFi Signal
    update_interval: 60s
  - platform: cse7766
    update_interval: 1s
    current:
      name: ${device_name} ${device_serial} Current
    voltage:
      name: ${device_name} ${device_serial} Voltage
    power:
      id: sonoff_power
      name: ${device_name} ${device_serial} Power
      filters:
        # Multiplication factor from W to kW is 0.001
        # Done so it can be measured through HA's Household consumption
        - multiply: 0.001
      unit_of_measurement: kW
      accuracy_decimals: 4
  - platform: total_daily_energy
    name: ${device_name} ${device_serial} Total Daily Energy
    power_id: sonoff_power

switch:
  - platform: gpio
    name: ${device_name} ${device_serial} Relay
    pin: GPIO12
    id: relay
  - platform: restart
    name: ${device_name} ${device_serial} Restart

# Enable time component to reset energy at midnight
time:
  - platform: sntp # could be platform: homeassistant
    timezone: America/Santiago