esphome:
  name: tuya-debugger

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up provisioning Wi-Fi credentials to the device over BLE
esp32_improv:
  authorizer: none

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:

debug:
  update_interval: 1s

# Logs hex strings by default
uart:
  - id: treadmill_controller
    rx_pin: 9
    baud_rate: 230400
    debug:
      direction: RX
      dummy_receiver: false
  - id: treadmill_console
    rx_pin: 16
    baud_rate: 230400
    debug:
      direction: RX
      dummy_receiver: false
