esphome:
  name: tuya-debugger

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up provisioning Wi-Fi credentials to the device over BLE
esp32_improv:
  authorizer: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:

# Logs hex strings by default
uart:
  - id: esp_cpu
    rx_pin: 22
    baud_rate: 9600
    debug:
      direction: RX
      dummy_receiver: false

  - id: tuya_mcu
    rx_pin: 21
    baud_rate: 9600
    debug:
      direction: RX
      dummy_receiver: false
